"""empty message

Revision ID: 9817a3095862
Revises: f266a25b730c
Create Date: 2020-06-25 11:49:34.369891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9817a3095862'
down_revision = 'f266a25b730c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'black_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'white_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_game_black_id'), 'game', ['black_id'], unique=False)
    op.create_index(op.f('ix_game_white_id'), 'game', ['white_id'], unique=False)
    op.drop_index('ix_game_black', table_name='game')
    op.drop_index('ix_game_white', table_name='game')
    # ### end Alembic commands ###
    op.drop_column('game','timestamp')
    op.add_column('game',sa.Column('timestamp', sa.TIMESTAMP, server_default=sa.func.now()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_game_white', 'game', ['white_id'], unique=False)
    op.create_index('ix_game_black', 'game', ['black_id'], unique=False)
    op.drop_index(op.f('ix_game_white_id'), table_name='game')
    op.drop_index(op.f('ix_game_black_id'), table_name='game')
    op.alter_column('game', 'white_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'black_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
