"""empty message

Revision ID: a7850f962924
Revises: e310ba60ab5b
Create Date: 2020-07-07 23:01:17.728689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7850f962924'
down_revision = 'e310ba60ab5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('fen_key', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'fen_key')
    # ### end Alembic commands ###
