"""empty message

Revision ID: e310ba60ab5b
Revises: 9817a3095862
Create Date: 2020-07-04 12:27:10.012507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e310ba60ab5b'
down_revision = '9817a3095862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_timestamp'), 'game', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_timestamp'), table_name='game')
    # ### end Alembic commands ###
