""" Added Game table

Revision ID: f266a25b730c
Revises: 47214944411d
Create Date: 2020-06-25 10:40:14.076983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f266a25b730c'
down_revision = '47214944411d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white_id', sa.Integer(), nullable=False),
    sa.Column('black_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('timecontrol', sa.String(length=50), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['black_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['white_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_timestamp'), 'game', ['timestamp'], unique=False)
    # ### end Alembic commands ###
    op.create_index(op.f('ix_game_white'), 'game', ['white_id'], unique=False)
    op.create_index(op.f('ix_game_black'), 'game', ['black_id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_timestamp'), table_name='game')
    # ### Inserted by CdV ###
    op.drop_index(op.f('ix_game_white'), table_name='game')
    op.drop_index(op.f('ix_game_black'), table_name='game')
    # ### End inserted by CdV ###
    op.drop_table('game')
    # ### end Alembic commands ###
